Added some additional error checking and messages.

diff --git a/netstereo/server/java/stereoserver.init b/netstereo/server/java/stereoserver.init
--- a/netstereo/server/java/stereoserver.init
+++ b/netstereo/server/java/stereoserver.init
@@ -8,6 +8,10 @@
 # description: Server for NetStereo application
 ##############################################################################
 # $Log$
+# Revision 1.4  2001/09/08 05:53:25  jheiss
+# Added lots of comments.
+# Replaced ps with a variable to facilitate multiple architectures.
+#
 # Revision 1.3  2001/07/24 20:28:23  jheiss
 # Added code to renice mpg123 to a higher priority.
 # Added error checking on the cd to the music directory.
@@ -97,10 +101,14 @@ PS="ps -e"  # Should work on SysV and modern Linux systems
 case "$1" in
 	start)
 		# Make sure the server isn't already running
-		$PS | awk '{print $1}' | grep -qs "^`cat $PIDFILE`\$"
-		if [ "$?" = 0 ]
+		if [ -f $PIDFILE ]
 		then
-			exit
+			$PS | awk '{print $1}' | grep -qs "^`cat $PIDFILE`\$"
+			if [ "$?" = 0 ]
+			then
+				echo "NetStereo server already running" >&2
+				exit
+			fi
 		fi
 
 		if [ -n "$SETVOLUME" ]
@@ -111,7 +119,7 @@ case "$1" in
 		cd $MUSICDIR
 		if [ "$?" != 0 ]
 		then
-			echo "Failed to cd to $MUSICDIR"
+			echo "Failed to cd to $MUSICDIR" >&2
 			exit 1
 		fi
 
@@ -137,7 +145,11 @@ case "$1" in
 		fi
 		;;
 	stop)
-		kill `cat $PIDFILE`
+		if [ -f $PIDFILE ]
+		then
+			kill `cat $PIDFILE`
+		fi
+
 		if [ x"$KILLMPG123" = "xtrue" ]
 		then
 			mpg123pid=`$PS | grep mpg123 | head -1 | awk '{print $1}'`
@@ -149,6 +161,7 @@ case "$1" in
 		;;
 	restart)
 		$0 stop
+		sleep 5
 		$0 start
 		;;
 	*)
